---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: heading
  label: Pages
- type: document
  path: content/data/about.md
  label: About Page
- type: document
  path: content/data/privacy.md
  label: Privacy Page
- type: heading
  label: Config
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "../images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
