---
label: Site Info
hide_body: true
fields:
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: siteUrl
  label: Site URL
  description: Necessary for generating “Sitemap”
pages:
- config.json
